Ejemplo/config/routes.rb
Ejemplo::Application.routes.draw do
  resources :clients

  resources :providers

  resources :users

end

Ejemplo/app/models/client.rb
class Client < ActiveRecord::Base
end

Ejemplo/app/models/provider.rb
class Provider < ActiveRecord::Base
end

Ejemplo/app/models/user.rb
class User < ActiveRecord::Base
end

Ejemplo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ejemplo/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:nombreClient, :telefonoClient, :direccionClient, :emailClient, :rfcClient, :razonsocialClient, :facebookClient, :linkedinClient)
    end
end

Ejemplo/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render action: 'show', status: :created, location: @provider }
      else
        format.html { render action: 'new' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:NombreProvider, :direccionProvider, :fechadasoProvider)
    end
end

Ejemplo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombreUser, :direccionUser, :telefonoUser, :emailUser, :contrasenaUser, :roluser)
    end
end

Ejemplo/app/helpers/application_helper.rb
module ApplicationHelper
end

Ejemplo/app/helpers/clients_helper.rb
module ClientsHelper
end

Ejemplo/app/helpers/providers_helper.rb
module ProvidersHelper
end

Ejemplo/app/helpers/users_helper.rb
module UsersHelper
end

Ejemplo/app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombreClient %><br>
    <%= f.text_field :nombreClient %>
  </div>
  <div class="field">
    <%= f.label :telefonoClient %><br>
    <%= f.text_field :telefonoClient %>
  </div>
  <div class="field">
    <%= f.label :direccionClient %><br>
    <%= f.text_field :direccionClient %>
  </div>
  <div class="field">
    <%= f.label :emailClient %><br>
    <%= f.text_field :emailClient %>
  </div>
  <div class="field">
    <%= f.label :rfcClient %><br>
    <%= f.text_field :rfcClient %>
  </div>
  <div class="field">
    <%= f.label :razonsocialClient %><br>
    <%= f.text_field :razonsocialClient %>
  </div>
  <div class="field">
    <%= f.label :facebookClient %><br>
    <%= f.text_field :facebookClient %>
  </div>
  <div class="field">
    <%= f.label :linkedinClient %><br>
    <%= f.text_field :linkedinClient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ejemplo/app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

Ejemplo/app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <thead>
    <tr>
      <th>Nombreclient</th>
      <th>Telefonoclient</th>
      <th>Direccionclient</th>
      <th>Emailclient</th>
      <th>Rfcclient</th>
      <th>Razonsocialclient</th>
      <th>Facebookclient</th>
      <th>Linkedinclient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.nombreClient %></td>
        <td><%= client.telefonoClient %></td>
        <td><%= client.direccionClient %></td>
        <td><%= client.emailClient %></td>
        <td><%= client.rfcClient %></td>
        <td><%= client.razonsocialClient %></td>
        <td><%= client.facebookClient %></td>
        <td><%= client.linkedinClient %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

Ejemplo/app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

Ejemplo/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombreclient:</strong>
  <%= @client.nombreClient %>
</p>

<p>
  <strong>Telefonoclient:</strong>
  <%= @client.telefonoClient %>
</p>

<p>
  <strong>Direccionclient:</strong>
  <%= @client.direccionClient %>
</p>

<p>
  <strong>Emailclient:</strong>
  <%= @client.emailClient %>
</p>

<p>
  <strong>Rfcclient:</strong>
  <%= @client.rfcClient %>
</p>

<p>
  <strong>Razonsocialclient:</strong>
  <%= @client.razonsocialClient %>
</p>

<p>
  <strong>Facebookclient:</strong>
  <%= @client.facebookClient %>
</p>

<p>
  <strong>Linkedinclient:</strong>
  <%= @client.linkedinClient %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

Ejemplo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ejemplo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ejemplo/app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NombreProvider %><br>
    <%= f.text_field :NombreProvider %>
  </div>
  <div class="field">
    <%= f.label :direccionProvider %><br>
    <%= f.text_field :direccionProvider %>
  </div>
  <div class="field">
    <%= f.label :fechadasoProvider %><br>
    <%= f.text_field :fechadasoProvider %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ejemplo/app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

Ejemplo/app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Nombreprovider</th>
      <th>Direccionprovider</th>
      <th>Fechadasoprovider</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.NombreProvider %></td>
        <td><%= provider.direccionProvider %></td>
        <td><%= provider.fechadasoProvider %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

Ejemplo/app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

Ejemplo/app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombreprovider:</strong>
  <%= @provider.NombreProvider %>
</p>

<p>
  <strong>Direccionprovider:</strong>
  <%= @provider.direccionProvider %>
</p>

<p>
  <strong>Fechadasoprovider:</strong>
  <%= @provider.fechadasoProvider %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>

Ejemplo/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombreUser %><br>
    <%= f.text_field :nombreUser %>
  </div>
  <div class="field">
    <%= f.label :direccionUser %><br>
    <%= f.text_field :direccionUser %>
  </div>
  <div class="field">
    <%= f.label :telefonoUser %><br>
    <%= f.text_field :telefonoUser %>
  </div>
  <div class="field">
    <%= f.label :emailUser %><br>
    <%= f.text_field :emailUser %>
  </div>
  <div class="field">
    <%= f.label :contrasenaUser %><br>
    <%= f.text_field :contrasenaUser %>
  </div>
  <div class="field">
    <%= f.label :roluser %><br>
    <%= f.text_field :roluser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ejemplo/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Ejemplo/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Nombreuser</th>
      <th>Direccionuser</th>
      <th>Telefonouser</th>
      <th>Emailuser</th>
      <th>Contrasenauser</th>
      <th>Roluser</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nombreUser %></td>
        <td><%= user.direccionUser %></td>
        <td><%= user.telefonoUser %></td>
        <td><%= user.emailUser %></td>
        <td><%= user.contrasenaUser %></td>
        <td><%= user.roluser %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Ejemplo/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Ejemplo/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombreuser:</strong>
  <%= @user.nombreUser %>
</p>

<p>
  <strong>Direccionuser:</strong>
  <%= @user.direccionUser %>
</p>

<p>
  <strong>Telefonouser:</strong>
  <%= @user.telefonoUser %>
</p>

<p>
  <strong>Emailuser:</strong>
  <%= @user.emailUser %>
</p>

<p>
  <strong>Contrasenauser:</strong>
  <%= @user.contrasenaUser %>
</p>

<p>
  <strong>Roluser:</strong>
  <%= @user.roluser %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>